<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.github.catageek</groupId>
	<artifactId>ByteCartAPI</artifactId>
	<name>ByteCartAPI</name>
	<description>API for ByteCart</description>
	<repositories>
		<repository>
			<id>central</id>
			<name>Maven Repository Switchboard</name>
			<layout>default</layout>
			<url>https://repo1.maven.org/maven2</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>spigot-repo</id>
			<url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
		</repository>
	</repositories>
	<distributionManagement>
		<site>
			<id>website</id>
			<url>http://catageek.free.fr/bytecart/maven/</url>
		</site>
		<repository>
			<id>repobcapi-rel</id>
			<name>bytecart.catageek.info API Releases</name>
			<url>ftp://ftpperso.free.fr/bytecart/maven/repositories/releases/</url>
		</repository>
		<snapshotRepository>
			<id>repobcapi-snap</id>
			<name>bytecart.catageek.info API Snapshots</name>
			<url>ftp://ftpperso.free.fr/bytecart/maven/repositories/snapshots/</url>
			<uniqueVersion>false</uniqueVersion>
		</snapshotRepository>
	</distributionManagement>
	<build>
		<sourceDirectory>src</sourceDirectory>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.14.1</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-site-plugin</artifactId>
				<version>3.21.0</version>
				<dependencies>
					<dependency><!-- add support for ssh/scp -->
						<groupId>org.apache.maven.wagon</groupId>
						<artifactId>wagon-ftp</artifactId>
						<version>3.5.3</version>
					</dependency>
				</dependencies>
			</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-shade-plugin</artifactId>
					<version>3.6.1</version>
					<configuration>
						<artifactSet>
							<excludes>
								<exclude>org.bukkit:bukkit:jar:*</exclude>
							</excludes>
						</artifactSet>
						<filters>
							<filter>
								<artifact>org.apache.commons:commons-lang3</artifact>
								<includes>
									<include>org/apache/commons/lang3/builder/**</include>
								</includes>
							</filter>
						</filters>
						<minimizeJar>true</minimizeJar>
					</configuration>
					<executions>
						<execution>
							<phase>package</phase>
							<goals>
								<goal>shade</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
		</plugins>
		<extensions>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>
				<artifactId>wagon-ftp</artifactId>
				<version>3.5.3</version>
			</extension>
		</extensions>
	</build>
	<properties>
		<spigot.version>1.21.10-R0.1-SNAPSHOT</spigot.version>
	</properties>
	<dependencies>
	   	<dependency>
           <groupId>org.spigotmc</groupId>
           <artifactId>spigot-api</artifactId>
           <version>${spigot.version}</version>
           <scope>provided</scope>
    	</dependency>
		<dependency>
    		<groupId>org.apache.commons</groupId>
    		<artifactId>commons-lang3</artifactId>
    		<version>3.19.0</version>
		</dependency>
	</dependencies>
	<version>4.0.0</version>
</project>